C0103 fixes for local variables
bug fixes

- syntax error in ws.py 309 fixed
- syntax error in dht.py 353 fixed
- using exc variable for all exceptions
- using dict literal in openbazaar_demon.py 207
- replaced verification-var where it was unnecessary

fixed undefined variable bugs in dht.py

reverted the change of the findID-attribute of the DHTSearch class

fixed TypeError: initialize() got an unexpected keyword argument 'db_connection'